AWSTemplateFormatVersion: 2010-09-09
Description: >-
  user-preference-api

Transform:
- AWS::Serverless-2016-10-31

Resources:
  userapi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user-preference-api
      Handler: 1.0/app.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 200
      Description: A Lambda function that handles the User API.
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - AmazonRDSFullAccess
        - AWSLambdaExecute
