AWSTemplateFormatVersion: 2010-09-09
Description: >-
  review-api

Transform:
- AWS::Serverless-2016-10-31

Resources:
  reviewapi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: review-api
      Handler: 1.0/app.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 200
      Description: A Lambda function that handles the Review API.
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - AmazonRDSFullAccess
        - AWSLambdaExecute
